export const AMENITY_LABEL_MAP: { [key: string]: string } = {
    bed: 'Cama',
    air: 'Aire acondicionado',
    wifi: 'Wi-Fi',
    tv: 'Televisión',
    shower: 'Ducha',
    amenities: 'Amenidades',
    parking: 'Estacionamiento',
    fridge: 'Refrigerador',
    desk: 'Escritorio',
    safe: 'Caja fuerte',
    'room-service': 'Servicio a la habitación',
    clock: 'Reloj despertador',
    fan: 'Ventilador',
    jacuzzi: 'Jacuzzi',
    balcony: 'Balcón',
};